[package]
name = "btc-to-ckb"
version = "0.1.0"
authors = ["vincent <vyclzn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../types", package = "toCKB-types" }
